# Generated by Django 6.0.2 on 2026-07-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "current_bill",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "simulated_bill",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "savings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
