# Generated by Django 6.0.7 on 2026-07-22 05:10

import billing.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="billingupload",
            name="file_size",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="billingupload",
            name="original_filename",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="billingupload",
            name="remarks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="billingupload",
            name="stored_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/billing/",
                validators=[billing.models.validate_csv_upload],
            ),
        ),
        migrations.AddField(
            model_name="billingupload",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("Uploaded", "Uploaded"),
                    ("Pending Processing", "Pending Processing"),
                    ("Failed", "Failed"),
                ],
                default="Uploaded",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="billingupload",
            name="upload_type",
            field=models.CharField(
                choices=[
                    ("Billing Report", "Billing Report"),
                    ("Usage Report", "Usage Report"),
                ],
                default="Billing Report",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="billingupload",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="billingupload",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="billingupload",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="billingupload",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="billingupload",
            name="title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="billingupload",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="billingupload",
            name="uploaded_file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
