# Generated by Django 6.0.7 on 2026-07-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_billingupload_file_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingrecord",
            name="availability_domain",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="billingrecord",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="billingrecord",
            name="currency",
            field=models.CharField(blank=True, default="USD", max_length=10),
        ),
        migrations.AddField(
            model_name="billingrecord",
            name="resource_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="billingrecord",
            name="usage_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="billingrecord",
            name="usage_quantity",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name="billingrecord",
            name="usage_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="billingrecord",
            name="usage_unit",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="billingupload",
            name="processing_logs",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="billingupload",
            name="processing_time",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="billingupload",
            name="rows_imported",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="billingupload",
            name="rows_read",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="billingupload",
            name="rows_skipped",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="billingrecord",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="billingrecord",
            name="usage_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="billingupload",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("Uploaded", "Uploaded"),
                    ("Processing", "Processing"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                ],
                default="Uploaded",
                max_length=50,
            ),
        ),
    ]
