# Generated by Django 6.0.7 on 2026-07-26 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_organization_organizationmembership_project"),
        (
            "billing",
            "0003_billingrecord_availability_domain_billingrecord_cost_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="billingupload",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_uploads",
                to="accounts.project",
            ),
        ),
    ]
