# Generated by Django 6.0.7 on 2026-07-26 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20260726_2016"),
        ("billing", "0004_billingupload_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingupload",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_uploads",
                to="accounts.project",
            ),
        ),
    ]
