# Generated by Django 6.0.7 on 2026-07-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_alter_billingupload_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingrecord",
            name="source_fingerprint",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="billingupload",
            name="upload_type",
            field=models.CharField(
                choices=[
                    ("Billing Report", "Billing Report"),
                    ("Usage Report", "Usage Report"),
                    ("OCI API Sync", "OCI API Sync"),
                ],
                default="Billing Report",
                max_length=50,
            ),
        ),
    ]
