# Generated by Django 6.0.7 on 2026-07-27 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20260726_2016"),
        ("oci_connector", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ociconnection",
            name="compartment_ocid",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="ociconnection",
            name="fingerprint",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="ociconnection",
            name="private_key_encrypted",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="ociconnection",
            name="project",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oci_connection",
                to="accounts.project",
            ),
        ),
        migrations.AddField(
            model_name="ociconnection",
            name="tenancy_ocid",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="ociconnection",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="ociconnection",
            name="user_ocid",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.CreateModel(
            name="OCIComputeInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ocid", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=100)),
                ("shape", models.CharField(max_length=100)),
                (
                    "ocpus",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "memory_in_gbs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("region", models.CharField(max_length=100)),
                ("compartment_id", models.CharField(max_length=255)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="oci_connector.ociconnection",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oci_instances",
                        to="accounts.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "ocid"],
                        name="oci_connect_project_bb97f7_idx",
                    ),
                    models.Index(
                        fields=["project", "state"],
                        name="oci_connect_project_24e4ea_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "ocid"), name="unique_project_compute_ocid"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OCILoadBalancer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ocid", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("shape", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("is_private", models.BooleanField(default=False)),
                ("ip_addresses", models.JSONField(blank=True, default=list)),
                ("region", models.CharField(max_length=100)),
                ("compartment_id", models.CharField(max_length=255)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="load_balancers",
                        to="oci_connector.ociconnection",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oci_load_balancers",
                        to="accounts.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "ocid"],
                        name="oci_connect_project_b0ace4_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "ocid"), name="unique_project_lb_ocid"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OCIObjectStorageBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("namespace", models.CharField(max_length=255)),
                ("approximate_size", models.BigIntegerField(blank=True, null=True)),
                ("approximate_count", models.BigIntegerField(blank=True, null=True)),
                (
                    "storage_tier",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("region", models.CharField(max_length=100)),
                ("compartment_id", models.CharField(max_length=255)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buckets",
                        to="oci_connector.ociconnection",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oci_buckets",
                        to="accounts.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "namespace", "name"],
                        name="oci_connect_project_426974_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "namespace", "name"),
                        name="unique_project_bucket_identity",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OCIPublicIp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ocid", models.CharField(max_length=255)),
                ("ip_address", models.CharField(max_length=100)),
                ("scope", models.CharField(max_length=100)),
                ("lifecycle_state", models.CharField(max_length=100)),
                (
                    "assigned_entity_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "assigned_entity_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_orphan", models.BooleanField(default=False)),
                ("region", models.CharField(max_length=100)),
                ("compartment_id", models.CharField(max_length=255)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_ips",
                        to="oci_connector.ociconnection",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oci_public_ips",
                        to="accounts.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "ocid"],
                        name="oci_connect_project_7641b7_idx",
                    ),
                    models.Index(
                        fields=["project", "is_orphan"],
                        name="oci_connect_project_a639d7_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "ocid"), name="unique_project_public_ip_ocid"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OCIResourceMetricSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_id", models.CharField(db_index=True, max_length=255)),
                ("metric_name", models.CharField(db_index=True, max_length=100)),
                ("date", models.DateField(db_index=True)),
                (
                    "average_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "maximum_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "minimum_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("sample_count", models.IntegerField(default=0)),
                (
                    "coverage_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_summaries",
                        to="oci_connector.ociconnection",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oci_metric_summaries",
                        to="accounts.project",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "resource_id", "metric_name", "date"),
                        name="unique_project_resource_metric_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OCISyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("ALL", "Full Sync"),
                            ("COST", "Cost Only"),
                            ("INVENTORY", "Inventory Only"),
                            ("METRICS", "Metrics Only"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("PARTIAL", "Completed with Warnings"),
                            ("FAILED", "Failed"),
                        ],
                        default="PROCESSING",
                        max_length=50,
                    ),
                ),
                ("records_created", models.IntegerField(default=0)),
                ("records_updated", models.IntegerField(default=0)),
                ("warning_summary", models.TextField(blank=True, default="")),
                ("error_summary", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="oci_connector.ociconnection",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oci_sync_logs",
                        to="accounts.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "started_at"],
                        name="oci_connect_project_fa0a34_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OCIVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ocid", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "volume_type",
                    models.CharField(
                        choices=[("BOOT", "Boot Volume"), ("BLOCK", "Block Volume")],
                        max_length=50,
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("size_in_gbs", models.BigIntegerField()),
                (
                    "attachment_state",
                    models.CharField(
                        choices=[
                            ("ATTACHED", "Attached"),
                            ("DETACHED", "Detached"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=50,
                    ),
                ),
                (
                    "attached_instance_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("region", models.CharField(max_length=100)),
                ("compartment_id", models.CharField(max_length=255)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volumes",
                        to="oci_connector.ociconnection",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oci_volumes",
                        to="accounts.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "ocid"],
                        name="oci_connect_project_4c4ec8_idx",
                    ),
                    models.Index(
                        fields=["project", "attachment_state"],
                        name="oci_connect_project_266c45_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "ocid"), name="unique_project_volume_ocid"
                    )
                ],
            },
        ),
    ]
