# Generated by Django 6.0.7 on 2026-07-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20260726_2016"),
        ("oci_connector", "0002_ociconnection_compartment_ocid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocicomputeinstance",
            name="inventory_status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Present"),
                    ("ABSENT", "Absent"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="PRESENT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ociloadbalancer",
            name="inventory_status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Present"),
                    ("ABSENT", "Absent"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="PRESENT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ociobjectstoragebucket",
            name="inventory_status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Present"),
                    ("ABSENT", "Absent"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="PRESENT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ocipublicip",
            name="inventory_status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Present"),
                    ("ABSENT", "Absent"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="PRESENT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ocivolume",
            name="inventory_status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Present"),
                    ("ABSENT", "Absent"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="PRESENT",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="ocicomputeinstance",
            index=models.Index(
                fields=["project", "inventory_status"],
                name="oci_connect_project_d98eb3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ociloadbalancer",
            index=models.Index(
                fields=["project", "inventory_status"],
                name="oci_connect_project_991ee7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ociobjectstoragebucket",
            index=models.Index(
                fields=["project", "inventory_status"],
                name="oci_connect_project_cdfc36_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ocipublicip",
            index=models.Index(
                fields=["project", "inventory_status"],
                name="oci_connect_project_a07735_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ocivolume",
            index=models.Index(
                fields=["project", "inventory_status"],
                name="oci_connect_project_c20f31_idx",
            ),
        ),
    ]
