# Generated by Django 6.0.2 on 2026-07-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("reason", models.TextField()),
                ("evidence", models.TextField(blank=True, default="")),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "estimated_savings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("risk_level", models.CharField(default="medium", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
