# Generated by Django 6.0.7 on 2026-07-24 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIExplanation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("ANOMALY", "Anomaly"), ("WASTE", "Waste")],
                        max_length=20,
                    ),
                ),
                ("source_id", models.PositiveIntegerField()),
                ("summary", models.TextField(blank=True, default="")),
                ("why_flagged", models.TextField(blank=True, default="")),
                ("evidence_summary", models.TextField(blank=True, default="")),
                ("financial_impact", models.TextField(blank=True, default="")),
                ("confidence_explanation", models.TextField(blank=True, default="")),
                ("recommended_next_step", models.TextField(blank=True, default="")),
                ("limitations", models.TextField(blank=True, default="")),
                ("model_name", models.CharField(max_length=100)),
                ("prompt_version", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("GENERATED", "Generated"), ("FAILED", "Failed")],
                        default="GENERATED",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("input_hash", models.CharField(db_index=True, max_length=64)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_explanations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "source_type", "source_id"],
                        name="ai_engine_a_user_id_2939b8_idx",
                    ),
                    models.Index(
                        fields=["input_hash"], name="ai_engine_a_input_h_529bf2_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "source_type", "source_id"),
                        name="unique_user_source_explanation",
                    )
                ],
            },
        ),
    ]
