# Generated by Django 6.0.7 on 2026-07-24 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_legacy_recommendations(apps, schema_editor):
    Recommendation = apps.get_model("ai_engine", "Recommendation")
    Recommendation.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0003_chatsession_chatmessage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="recommendation",
            old_name="created_at",
            new_name="detected_at",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="estimated_savings",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="reason",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="risk_level",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="title",
        ),
        migrations.AddField(
            model_name="recommendation",
            name="ai_explanation_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="ai_explanation_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="current_monthly_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="estimated_monthly_savings",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="fingerprint",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="identity_type",
            field=models.CharField(default="unknown", max_length=20),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="identity_value",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="limitations",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("CRITICAL", "Critical"),
                ],
                default="LOW",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="recommendation_scope",
            field=models.CharField(
                choices=[
                    ("RESOURCE", "Resource"),
                    ("SERVICE_REGION", "Service/Region"),
                ],
                default="RESOURCE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="recommendation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RIGHTSIZE_REVIEW", "Rightsizing Review"),
                    ("RESERVED_CAPACITY_REVIEW", "Reserved Capacity Review"),
                    ("STORAGE_OPTIMIZATION", "Storage Optimization"),
                    ("BACKUP_POLICY_REVIEW", "Backup Policy Review"),
                    ("COST_PATTERN_REVIEW", "Cost Pattern Review"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="recommended_action",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="region",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="resource_id",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="resource_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="savings_source",
            field=models.CharField(
                choices=[
                    ("WASTE_FINDING", "Waste Finding"),
                    ("DETERMINISTIC_RULE", "Deterministic Rule"),
                    ("NONE", "None"),
                ],
                default="NONE",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="service_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="source_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WASTE_FINDING", "Waste Finding"),
                    ("COST_ANOMALY", "Cost Anomaly"),
                    ("BILLING_PATTERN", "Billing Pattern"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("REVIEWED", "Reviewed"),
                    ("ACCEPTED", "Accepted"),
                    ("DISMISSED", "Dismissed"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="confidence",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="LOW",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["user", "status"], name="ai_engine_r_user_id_aa759f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["user", "priority"], name="ai_engine_r_user_id_50eb3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["user", "recommendation_type"],
                name="ai_engine_r_user_id_2df73b_idx",
            ),
        ),
        # 1. Clear unowned legacy recommendation data
        migrations.RunPython(delete_legacy_recommendations),
        # 2. Make non-nullable constraints final
        migrations.AlterField(
            model_name="recommendation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="recommendation_type",
            field=models.CharField(
                choices=[
                    ("RIGHTSIZE_REVIEW", "Rightsizing Review"),
                    ("RESERVED_CAPACITY_REVIEW", "Reserved Capacity Review"),
                    ("STORAGE_OPTIMIZATION", "Storage Optimization"),
                    ("BACKUP_POLICY_REVIEW", "Backup Policy Review"),
                    ("COST_PATTERN_REVIEW", "Cost Pattern Review"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("WASTE_FINDING", "Waste Finding"),
                    ("COST_ANOMALY", "Cost Anomaly"),
                    ("BILLING_PATTERN", "Billing Pattern"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="fingerprint",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
