# Generated by Django 6.0.7 on 2026-07-26 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_organization_organizationmembership_project"),
        ("ai_engine", "0004_update_recommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiexplanation",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_explanations",
                to="accounts.project",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to="accounts.project",
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="accounts.project",
            ),
        ),
    ]
