# Generated by Django 6.0.7 on 2026-07-26 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20260726_2016"),
        ("ai_engine", "0005_aiexplanation_project_chatsession_project_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="aiexplanation",
            name="unique_user_source_explanation",
        ),
        migrations.RemoveIndex(
            model_name="aiexplanation",
            name="ai_engine_a_user_id_2939b8_idx",
        ),
        migrations.RemoveIndex(
            model_name="chatsession",
            name="ai_engine_c_user_id_13c391_idx",
        ),
        migrations.RemoveIndex(
            model_name="recommendation",
            name="ai_engine_r_user_id_aa759f_idx",
        ),
        migrations.RemoveIndex(
            model_name="recommendation",
            name="ai_engine_r_user_id_50eb3e_idx",
        ),
        migrations.RemoveIndex(
            model_name="recommendation",
            name="ai_engine_r_user_id_2df73b_idx",
        ),
        migrations.AlterField(
            model_name="aiexplanation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_explanations",
                to="accounts.project",
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to="accounts.project",
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="accounts.project",
            ),
        ),
        migrations.AddIndex(
            model_name="aiexplanation",
            index=models.Index(
                fields=["project", "source_type", "source_id"],
                name="ai_engine_a_project_30af92_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["project", "user", "updated_at"],
                name="ai_engine_c_project_4aee2e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["project", "status"], name="ai_engine_r_project_c3766c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["project", "priority"], name="ai_engine_r_project_cecf13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["project", "recommendation_type"],
                name="ai_engine_r_project_5a92b4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiexplanation",
            constraint=models.UniqueConstraint(
                fields=("project", "source_type", "source_id"),
                name="unique_project_source_explanation",
            ),
        ),
    ]
