# Generated by Django 6.0.2 on 2026-07-22 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "billing",
            "0003_billingrecord_availability_domain_billingrecord_cost_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostAnomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anomaly_type",
                    models.CharField(
                        choices=[
                            ("DAILY_SPIKE", "Daily Spike"),
                            ("SERVICE_SPIKE", "Service Spike"),
                            ("RESOURCE_SPIKE", "Resource Spike"),
                            ("UNUSUAL_GROWTH", "Unusual Growth"),
                        ],
                        max_length=50,
                    ),
                ),
                ("detected_date", models.DateField()),
                (
                    "service_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "resource_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("region", models.CharField(blank=True, default="", max_length=200)),
                ("actual_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("expected_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "deviation_percentage",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("z_score", models.FloatField(blank=True, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("REVIEWED", "Reviewed"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing_upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_anomalies",
                        to="billing.billingupload",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_anomalies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "detected_date"],
                        name="analytics_c_user_id_cf2c44_idx",
                    ),
                    models.Index(
                        fields=["user", "severity"],
                        name="analytics_c_user_id_783c81_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="analytics_c_user_id_027c51_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "user",
                            "anomaly_type",
                            "detected_date",
                            "service_name",
                            "resource_id",
                            "resource_name",
                        ),
                        name="unique_user_anomaly_event",
                    )
                ],
            },
        ),
    ]
