# Generated by Django 6.0.2 on 2026-07-23 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("waste_type", models.CharField(max_length=50)),
                (
                    "resource_key",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "resource_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("service_name", models.CharField(max_length=200)),
                ("region", models.CharField(blank=True, default="", max_length=200)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("first_seen", models.DateField()),
                ("last_seen", models.DateField()),
                ("observation_days", models.IntegerField()),
                ("calendar_span_days", models.IntegerField()),
                ("coverage_ratio", models.DecimalField(decimal_places=4, max_digits=5)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "average_daily_cost",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "estimated_monthly_cost",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "estimated_monthly_savings",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                ("evidence", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("REVIEWED", "Reviewed"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_findings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="analytics_w_user_id_a98232_idx"
                    ),
                    models.Index(
                        fields=["user", "waste_type"],
                        name="analytics_w_user_id_6da5b8_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "user",
                            "waste_type",
                            "resource_key",
                            "service_name",
                            "currency",
                        ),
                        name="unique_user_waste_event",
                    )
                ],
            },
        ),
    ]
