# Generated by Django 6.0.7 on 2026-07-26 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_organization_organizationmembership_project"),
        ("analytics", "0002_wastefinding"),
    ]

    operations = [
        migrations.AddField(
            model_name="costanomaly",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_anomalies",
                to="accounts.project",
            ),
        ),
        migrations.AddField(
            model_name="wastefinding",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waste_findings",
                to="accounts.project",
            ),
        ),
    ]
