# Generated by Django 6.0.7 on 2026-07-26 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20260726_2016"),
        ("analytics", "0003_costanomaly_project_wastefinding_project"),
        ("billing", "0004_billingupload_project"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="costanomaly",
            name="unique_user_anomaly_event",
        ),
        migrations.RemoveConstraint(
            model_name="wastefinding",
            name="unique_user_waste_event",
        ),
        migrations.RemoveIndex(
            model_name="costanomaly",
            name="analytics_c_user_id_cf2c44_idx",
        ),
        migrations.RemoveIndex(
            model_name="costanomaly",
            name="analytics_c_user_id_783c81_idx",
        ),
        migrations.RemoveIndex(
            model_name="costanomaly",
            name="analytics_c_user_id_027c51_idx",
        ),
        migrations.RemoveIndex(
            model_name="wastefinding",
            name="analytics_w_user_id_a98232_idx",
        ),
        migrations.RemoveIndex(
            model_name="wastefinding",
            name="analytics_w_user_id_6da5b8_idx",
        ),
        migrations.AlterField(
            model_name="costanomaly",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_anomalies",
                to="accounts.project",
            ),
        ),
        migrations.AlterField(
            model_name="wastefinding",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waste_findings",
                to="accounts.project",
            ),
        ),
        migrations.AddIndex(
            model_name="costanomaly",
            index=models.Index(
                fields=["project", "detected_date"],
                name="analytics_c_project_0f9263_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="costanomaly",
            index=models.Index(
                fields=["project", "severity"], name="analytics_c_project_f90365_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costanomaly",
            index=models.Index(
                fields=["project", "status"], name="analytics_c_project_61bed0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wastefinding",
            index=models.Index(
                fields=["project", "status"], name="analytics_w_project_0bf051_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wastefinding",
            index=models.Index(
                fields=["project", "waste_type"], name="analytics_w_project_48529e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="costanomaly",
            constraint=models.UniqueConstraint(
                fields=(
                    "project",
                    "anomaly_type",
                    "detected_date",
                    "service_name",
                    "resource_id",
                    "resource_name",
                ),
                name="unique_project_anomaly_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="wastefinding",
            constraint=models.UniqueConstraint(
                fields=(
                    "project",
                    "waste_type",
                    "resource_key",
                    "service_name",
                    "currency",
                ),
                name="unique_project_waste_event",
            ),
        ),
    ]
