# Generated by Django 6.0.7 on 2026-07-26 14:46

import hashlib
from django.db import migrations
from django.utils.text import slugify


def backfill_orgs_and_projects(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Organization = apps.get_model("accounts", "Organization")
    OrganizationMembership = apps.get_model("accounts", "OrganizationMembership")
    Project = apps.get_model("accounts", "Project")
    
    BillingUpload = apps.get_model("billing", "BillingUpload")
    CostAnomaly = apps.get_model("analytics", "CostAnomaly")
    WasteFinding = apps.get_model("analytics", "WasteFinding")
    Recommendation = apps.get_model("ai_engine", "Recommendation")
    AIExplanation = apps.get_model("ai_engine", "AIExplanation")
    ChatSession = apps.get_model("ai_engine", "ChatSession")
    
    seen_fingerprints = set()
    for user in User.objects.all():
        org_name = f"{user.username}'s Org"
        org_slug = slugify(user.username)
        
        # Avoid duplicate slug conflicts
        counter = 1
        base_slug = org_slug
        while Organization.objects.filter(slug=org_slug).exists():
            org_slug = f"{base_slug}-{counter}"
            counter += 1
            
        org = Organization.objects.create(name=org_name, slug=org_slug)
        
        # Create OWNER membership
        OrganizationMembership.objects.create(
            user=user,
            organization=org,
            role="OWNER"
        )
        
        # Create Default Project
        proj = Project.objects.create(
            organization=org,
            name="Default Project",
            slug="default-project",
            description="Automatic default project for existing data."
        )
        
        # Associate user's existing records with this project
        BillingUpload.objects.filter(uploaded_by=user).update(project=proj)
        CostAnomaly.objects.filter(user=user).update(project=proj)
        WasteFinding.objects.filter(user=user).update(project=proj)
        Recommendation.objects.filter(user=user).update(project=proj)
        AIExplanation.objects.filter(user=user).update(project=proj)
        ChatSession.objects.filter(user=user).update(project=proj)
        
        # Update recommendation fingerprints deterministically with the new project formula
        for rec in Recommendation.objects.filter(project=proj):
            raw_str = f"{proj.id}|{rec.recommendation_type}|{rec.recommendation_scope}|{rec.source_type or ''}|{rec.source_id or ''}|{rec.identity_type}|{rec.identity_value}|{rec.service_name}|{rec.region}|{rec.currency}"
            fp = hashlib.sha256(raw_str.encode('utf-8')).hexdigest()
            if fp in seen_fingerprints:
                rec.delete()
            else:
                rec.fingerprint = fp
                rec.save()
                seen_fingerprints.add(fp)


def reverse_backfill(apps, schema_editor):
    Organization = apps.get_model("accounts", "Organization")
    Organization.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_organization_organizationmembership_project"),
        ("ai_engine", "0005_aiexplanation_project_chatsession_project_and_more"),
        ("analytics", "0003_costanomaly_project_wastefinding_project"),
        ("billing", "0004_billingupload_project"),
    ]

    operations = [
        migrations.RunPython(backfill_orgs_and_projects, reverse_backfill),
    ]

